int8 TrackedDeviceClass_Invalid = 0           # the ID was not valid.
int8 TrackedDeviceClass_HMD = 1               # Head-Mounted Displays
int8 TrackedDeviceClass_Controller = 2        # Tracked controllers
int8 TrackedDeviceClass_GenericTracker = 3    # Generic trackers, similar to controllers
int8 TrackedDeviceClass_TrackingReference = 4 # Camera and base stations that serve as tracking reference points
int8 TrackedDeviceClass_DisplayRedirect = 5   # Accessories that aren't necessarily tracked themselves, but may redirect video output from other tracked devices
