int8 TrackedControllerRole_Invalid = 0   # Invalid value for controller type
int8 TrackedControllerRole_LeftHand = 1  # Tracked device associated with the left hand
int8 TrackedControllerRole_RightHand = 2 # Tracked device associated with the right hand
int8 TrackedControllerRole_OptOut = 3    # Tracked device is opting out of left/right hand selection
int8 TrackedControllerRole_Treadmill = 4 # Tracked device is a treadmill
